/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  docs: [
    'overview',
    {
      Guides: ['guides', 'guides/swap', 'guides/sdk-demo', 'guides/farm', 'guides/cpi']
    },
    {
      'Swap Widget': ['swap-widget/getting-started', 'swap-widget/react', 'swap-widget/react-lib', 'swap-widget/iframe']
    },
    'showcase',
    'faq',
    {
      'Resources': ['resources/links', 'resources/token-list', 'resources/liquidity-pools']
    },
    'changelog'
  ],
  API: [
    {
      type: 'autogenerated',
      dirName: 'api'
    }
  ]
};

module.exports = sidebars;
